### ISSUE TITLE
Implement item purchasing for users

### ISSUE THREAD

**Issue by Chr728** [JamesPartsafas/online-store#11]
Initiator - Signed in user

As a signed-in user, I want to be able to purchase items so that it can be delivered to my doorstep upon checkout.

Story points: 13
Risk: Medium
Priority: Medium

-In case the user is not signed  then direct the user to sign in before they can add something to their cart( if it is not an existing customer then make them sign up first and then they can add something to their cart)

- [x]  let the user always be able to check their cart 
- [x]  once they are in their cart, let the user able to see the total with taxes added and let them checkout and pay
- [x]  Allow order viewing and cancellation
- [x]  Allow user to add a payment method

Child tasks are #93 #94

Acceptance test
- As a signed in user, add products to cart.
- When going to the cart page, all items should be displayed with a price breakdown.
- On clicking the purchase button, an error should be displayed indicating payment credentials are needed.
- Upon entering a credit card number and clicking purchase, the order is added to the user's order history and the cart is cleared.
- User is redirected to order page to view the order just made.

**Comment by JamesPartsafas** [comment]
All items implement. Story can be closed.
