### ISSUE TITLE
Allow users to modify their cart content

### ISSUE THREAD

**Issue by JamesPartsafas** [JamesPartsafas/online-store#31]
Initiator - signed-in users

As a signed-in user, I want to be able to add and remove items in my cart in case I change my mind on some of the things I want to or do not want to purchase.

Story points: 7
Risk: Low
Priority: Medium

Users, after signing in, should be able to add items to their cart, with varying quantities, as well as remove them. There should be a cart page where they can view all items currently added in and modify them, if necessary.

- Signed in user must be able to add to the cart
- Signed in user must be able to change cart item quantity
- Signed in user must be able to remove items from his cart

Tasks:

- [x] add the functionality of adding products to the cart
- [x] add the back end functionality 
- [x] have the cart page ready
- [x]  add controls and style cart page.

Child items: #89, #95, #111

Acceptance test
- Upon visiting the site, sign in as a regular user
- Go to any product page and click the "add to cart button"
- Click the cart button. The item added to the cart should be displayed.
- When clicking the increment or decrement buttons, the quantity of the item should change.
- If an item quantity goes to 0, remove it from the cart.

**Comment by JamesPartsafas** [comment]
All child tasks complete. Story can be closed.
